
int GetChallengeID(int a, int b, int c) { return callNative(0x18AFD0,3,a,b,c); }
int IsInChallenge(int a, int b, int c) { return callNative(0x18AF60,3,a,b,c); }
int IsChallengeComplete(int a, int b, int c) { return callNative(0x18AECC,3,a,b,c); }
int IsChallengeReferee(int a, int b, int c) { return callNative(0x18AE70,3,a,b,c); }
int IsChallengeTimerRunning(int a, int b, int c) { return callNative(0x18ACD4,3,a,b,c); }
int SetChallengeTimer(int a, int b, int c) { return callNative(0x18AC54,3,a,b,c); }
int SetCutsceneCompetitorPriorityHighestBounty(int a, int b, int c) { return callNative(0x18AC10,3,a,b,c); }
int GetCompetitorTeam(int a, int b, int c) { return callNative(0x18A7CC,3,a,b,c); }
int GetTeamChallengePartIndex(int a, int b, int c) { return callNative(0x18A864,3,a,b,c); }
int IsPlayerCollidingWithRaceCar(int a, int b, int c) { return callNative(0x18A5A4,3,a,b,c); }
int IsPlayerCollidingWithTraffic(int a, int b, int c) { return callNative(0x18A4A4,3,a,b,c); }
int SetHitTrafficVehicle(int a, int b, int c) { return callNative(0x18A408,3,a,b,c); }
int HasPlayerHitTrafficVehicleBefore(int a, int b, int c) { return callNative(0x18A30C,3,a,b,c); }
int IsPlayerCollidingWithWorld(int a, int b, int c) { return callNative(0x18A128,3,a,b,c); }
int GetCollisionCompetitorIndex(int a, int b, int c) { return callNative(0x18A194,3,a,b,c); }
int GetStartingGridIndex(int a, int b, int c) { return callNative(0x18A018,3,a,b,c); }
int HasAIReachedPartIndex(int a, int b, int c) { return callNative(0x189288,3,a,b,c); }
int SetTeamActivatesTimeout(int a, int b, int c) { return callNative(0x1891DC,3,a,b,c); }
int GetCheckpointCount(int a, int b, int c) { return callNative(0x1897FC,3,a,b,c); }
int GetCheckpointID(int a, int b, int c) { return callNative(0x189F80,3,a,b,c); }
int IsPlayerWithinTargetRange(int a, int b, int c) { return callNative(0x189AE4,3,a,b,c); }
int GetStartPositionID(int a, int b, int c) { return callNative(0x189870,3,a,b,c); }
int GetChallengeTime(int a, int b, int c) { return callNative(0x1890B0,3,a,b,c); }
int SetReporterValue(int a, int b, int c) { return callNative(0x188EDC,3,a,b,c); }
int SetChallengeLayoutGroup(int a, int b, int c) { return callNative(0x188E84,3,a,b,c); }
int ClearLayoutGroup(int a, int b, int c) { return callNative(0x188E0C,3,a,b,c); }
int FetchSpeedwallResults(int a, int b, int c) { return callNative(0x18904C,3,a,b,c); }
int SetAutologGameReportResults(int a, int b, int c) { return callNative(0x187658,3,a,b,c); }
int StartAutologGameReport(int a, int b, int c) { return callNative(0x187AC8,3,a,b,c); }
int StopAutologGameReport(int a, int b, int c) { return callNative(0x187874,3,a,b,c); }
int IsAutologGameReportRunning(int a, int b, int c) { return callNative(0x187A6C,3,a,b,c); }
int SetupRaceBalancing(int a, int b, int c) { return callNative(0x187440,3,a,b,c); }
int IsRaceBalancingManagerReady(int a, int b, int c) { return callNative(0x1873DC,3,a,b,c); }
int SetupRaceDistanceToFinish(int a, int b, int c) { return callNative(0x1871B4,3,a,b,c); }
int GetCurrentCheckpointIndex(int a, int b, int c) { return callNative(0x1870AC,3,a,b,c); }
int GetTargetCheckpointID(int a, int b, int c) { return callNative(0x189EF4,3,a,b,c); }
int UpdateCheckpoints(int a, int b, int c) { return callNative(0x186E64,3,a,b,c); }
int SetupInterceptorBalancing(int a, int b, int c) { return callNative(0x186A74,3,a,b,c); }
int IsInterceptorBalancingDataLoaded(int a, int b, int c) { return callNative(0x1869CC,3,a,b,c); }
int SetupChallengeChevrons(int a, int b, int c) { return callNative(0x1866CC,3,a,b,c); }
int SetupChevronColours(int a, int b, int c) { return callNative(0x186540,3,a,b,c); }
int ClearChevronColours(int a, int b, int c) { return callNative(0x186690,3,a,b,c); }
int SetupRestrictedRoadSections(int a, int b, int c) { return callNative(0x18617C,3,a,b,c); }
int AddChallengeBackstops(int a, int b, int c) { return callNative(0x185E1C,3,a,b,c); }
int ClearChallengeBackstops(int a, int b, int c) { return callNative(0x185DE0,3,a,b,c); }
int SendMostWantedNetworkEvent(int a, int b, int c) { return callNative(0x185DBC,3,a,b,c); }
int GetMostWantedCompetitor(int a, int b, int c) { return callNative(0x185D34,3,a,b,c); }
int GetCompetitorRoad(int a, int b, int c) { return callNative(0x185C54,3,a,b,c); }
int GetTargetCompetitor(int a, int b, int c) { return callNative(0x185CD0,3,a,b,c); }
int GetRoadHeadingSpeech(int a, int b, int c) { return callNative(0x185C14,3,a,b,c); }
int GetRoadScriptLine(int a, int b, int c) { return callNative(0x1856E8,3,a,b,c); }
int GetVehicleScriptLine(int a, int b, int c) { return callNative(0x18569C,3,a,b,c); }
int GetRoadSpeechRejoined(int a, int b, int c) { return callNative(0x18565C,3,a,b,c); }
int IsRoadShortCut(int a, int b, int c) { return callNative(0x1855C0,3,a,b,c); }
int GetTurnDirection(int a, int b, int c) { return callNative(0x185734,3,a,b,c); }
int AreMessagesLoaded(int a, int b, int c) { return callNative(0x189004,3,a,b,c); }
int SetTimeoutTotalTime(int a, int b, int c) { return callNative(0x187384,3,a,b,c); }
int IsTimeoutTimeValid(int a, int b, int c) { return callNative(0x187320,3,a,b,c); }
int GetCompetitorPosition(int a, int b, int c) { return callNative(0x18A8F8,3,a,b,c); }
int GetChallengeParam(int a, int b, int c) { return callNative(0x1894E8,3,a,b,c); }
int GetChallengeParamCount(int a, int b, int c) { return callNative(0x1893B4,3,a,b,c); }
int GetCurrentMedal(int a, int b, int c) { return callNative(0x188D58,3,a,b,c); }
int SetChallengeSuccessful(int a, int b, int c) { return callNative(0x188A50,3,a,b,c); }
int IsChallengeSuccessful(int a, int b, int c) { return callNative(0x1889CC,3,a,b,c); }
int HasTimedOut(int a, int b, int c) { return callNative(0x188944,3,a,b,c); }
int IsTimeoutActive(int a, int b, int c) { return callNative(0x18859C,3,a,b,c); }
int GetBountyForRaceFinishPosition(int a, int b, int c) { return callNative(0x188260,3,a,b,c); }
int GetBountyForMedal(int a, int b, int c) { return callNative(0x18813C,3,a,b,c); }
int GetOnlineBounty(int a, int b, int c) { return callNative(0x188028,3,a,b,c); }
int SetCopsCanSlipstream(int a, int b, int c) { return callNative(0x187FB8,3,a,b,c); }
int RequestChallengeMode(int a, int b, int c) { return callNative(0x1864EC,3,a,b,c); }
int SetPersonalBest(int a, int b, int c) { return callNative(0x187F18,3,a,b,c); }
int GetPersonalBest(int a, int b, int c) { return callNative(0x187DFC,3,a,b,c); }
int HasTakenTopOfSpeedwall(int a, int b, int c) { return callNative(0x187CF4,3,a,b,c); }
int GetBeatItTime(int a, int b, int c) { return callNative(0x187C0C,3,a,b,c); }
int SetupChallengeWeaponAvailability(int a, int b, int c) { return callNative(0x186B64,3,a,b,c); }
int IsWeaponAvailabilityDataLoaded(int a, int b, int c) { return callNative(0x186B14,3,a,b,c); }
int SetCutsceneCompetitorForPursuitRace(int a, int b, int c) { return callNative(0x18A9D0,3,a,b,c); }
int RecordChallengeAttempt(int a, int b, int c) { return callNative(0x186464,3,a,b,c); }
int HasRanOutOfTime(int a, int b, int c) { return callNative(0x188B50,3,a,b,c); }
int IsPlayerAggressiveHitting(int a, int b, int c) { return callNative(0x185554,3,a,b,c); }
int UpdateTimePenalties(int a, int b, int c) { return callNative(0x188348,3,a,b,c); }
int SetChallengeWonByCops(int a, int b, int c) { return callNative(0x188AE8,3,a,b,c); }
int GetInterceptorResultsSequence(int a, int b, int c) { return callNative(0x1853D0,3,a,b,c); }
int GetHPOfflineResultsSequence(int a, int b, int c) { return callNative(0x185284,3,a,b,c); }
int GetHPOnlineResultsSequence(int a, int b, int c) { return callNative(0x18513C,3,a,b,c); }
int GetMostWantedResultsSequence(int a, int b, int c) { return callNative(0x184FF0,3,a,b,c); }
int GetRaceResultsSequence(int a, int b, int c) { return callNative(0x184EA8,3,a,b,c); }
int GetRapidResponseResultsSequence(int a, int b, int c) { return callNative(0x184D5C,3,a,b,c); }
int GetRoadTimesResultsSequence(int a, int b, int c) { return callNative(0x184C14,3,a,b,c); }
int GetGauntletResultsSequence(int a, int b, int c) { return callNative(0x184ACC,3,a,b,c); }
int UpdateMedalAwarded(int a, int b, int c) { return callNative(0x188D08,3,a,b,c); }
int ResetChallengeGameModeLayoutToDefault(int a, int b, int c) { return callNative(0x188E4C,3,a,b,c); }
int PlayIntroSounds(int a, int b, int c) { return callNative(0x1885F0,3,a,b,c); }
int AllowNetworkPlayersToJoinGame(int a, int b, int c) { return callNative(0x1888E0,3,a,b,c); }
int SetCutsceneCompetitorPriorityLowestBounty(int a, int b, int c) { return callNative(0x18ABCC,3,a,b,c); }
int GetValue(int a, int b, int c) { return callNative(0x184140,3,a,b,c); }
int GetFrameCount(int a, int b, int c) { return callNative(0x1840E0,3,a,b,c); }
int GetSimTimeStep(int a, int b, int c) { return callNative(0x183A90,3,a,b,c); }
int GetSimTime(int a, int b, int c) { return callNative(0x183B34,3,a,b,c); }
int GetScorableCompetitorCount(int a, int b, int c) { return callNative(0x1831E0,3,a,b,c); }
int IsCompetitorActive(int a, int b, int c) { return callNative(0x18316C,3,a,b,c); }
int GetCompetitorTeam_1(int a, int b, int c) { return callNative(0x1830EC,3,a,b,c); }
int GetLocalPlayerCompetitorIndex(int a, int b, int c) { return callNative(0x183098,3,a,b,c); }
int GetCompetitorName(int a, int b, int c) { return callNative(0x182FD4,3,a,b,c); }
int GetCompetitorType(int a, int b, int c) { return callNative(0x182F54,3,a,b,c); }
int SetCarLocked(int a, int b, int c) { return callNative(0x183C78,3,a,b,c); }
int DisableMenuControls(int a, int b, int c) { return callNative(0x183BC4,3,a,b,c); }
int SetCarFrozen(int a, int b, int c) { return callNative(0x184030,3,a,b,c); }
int SetCarStill(int a, int b, int c) { return callNative(0x183E88,3,a,b,c); }
int IsRemoteCompetitor(int a, int b, int c) { return callNative(0x183E00,3,a,b,c); }
int IsOnline(int a, int b, int c) { return callNative(0x182EA8,3,a,b,c); }
int IsInOnlineEvent(int a, int b, int c) { return callNative(0x182EFC,3,a,b,c); }
int AddSynchronisedNetworkEvent(int a, int b, int c) { return callNative(0x17F500,3,a,b,c); }
int GetSynchronisedNetworkEventTime(int a, int b, int c) { return callNative(0x197598,3,a,b,c); }
int SetTimeOfDay(int a, int b, int c) { return callNative(0x1842A8,3,a,b,c); }
int ResetTimeOfDayDefaults(int a, int b, int c) { return callNative(0x184A78,3,a,b,c); }
int AreLobbyParamsValid(int a, int b, int c) { return callNative(0x184448,3,a,b,c); }
int ReportTelemetryLiteGameModeStart(int a, int b, int c) { return callNative(0x197574,3,a,b,c); }
int GetNumOnlinePlayers(int a, int b, int c) { return callNative(0x197514,3,a,b,c); }
int RegisterBountyScore(int a, int b, int c) { return callNative(0x1973D4,3,a,b,c); }
int GetScoreValue(int a, int b, int c) { return callNative(0x1972AC,3,a,b,c); }
int SetBustWreckSequences(int a, int b, int c) { return callNative(0x1965B8,3,a,b,c); }
int DebugPrint(int a, int b, int c) { return callNative(0x1964C0,3,a,b,c); }
int print(int a, int b, int c) { return callNative(0x196484,3,a,b,c); }
int HasSetFinalTime(int a, int b, int c) { return callNative(0x183D2C,3,a,b,c); }
int IsExitLoadingScreenButtonPressed(int a, int b, int c) { return callNative(0x183FAC,3,a,b,c); }
int IsHardStopInProgress(int a, int b, int c) { return callNative(0x1963FC,3,a,b,c); }
int SetChallengeRaceTarget(int a, int b, int c) { return callNative(0x1846F4,3,a,b,c); }
int InvalidateRaceTarget(int a, int b, int c) { return callNative(0x184648,3,a,b,c); }
int GetDistanceToFinish(int a, int b, int c) { return callNative(0x184588,3,a,b,c); }
int GetRaceDistance(int a, int b, int c) { return callNative(0x1844B0,3,a,b,c); }
int ClearAllChevrons(int a, int b, int c) { return callNative(0x196564,3,a,b,c); }
int EnableNitrousBalancing(int a, int b, int c) { return callNative(0x1964FC,3,a,b,c); }
int GetRoadStartPosition(int a, int b, int c) { return callNative(0x1839C4,3,a,b,c); }
int GetRoadStartDirection(int a, int b, int c) { return callNative(0x1838A0,3,a,b,c); }
int GetRoadCount(int a, int b, int c) { return callNative(0x18382C,3,a,b,c); }
int TeleportToNamedRoad(int a, int b, int c) { return callNative(0x18328C,3,a,b,c); }
int GetCompetitorDistance(int a, int b, int c) { return callNative(0x196F6C,3,a,b,c); }
int IsCompetitorWithinVisibilityCone(int a, int b, int c) { return callNative(0x196CA0,3,a,b,c); }
int GetCompetitorDistanceToTarget(int a, int b, int c) { return callNative(0x1970B8,3,a,b,c); }
int EnableLocalRaceCarRumble(int a, int b, int c) { return callNative(0x19723C,3,a,b,c); }
int SetMinimumCollisionDamage(int a, int b, int c) { return callNative(0x197200,3,a,b,c); }
int SetEnableLuxurySounds(int a, int b, int c) { return callNative(0x196218,3,a,b,c); }
int SetMaxGas(int a, int b, int c) { return callNative(0x196AF8,3,a,b,c); }
int SetMinBrake(int a, int b, int c) { return callNative(0x196950,3,a,b,c); }
int SetMinHandbrake(int a, int b, int c) { return callNative(0x1967A8,3,a,b,c); }
int SetSteerDirection(int a, int b, int c) { return callNative(0x1966AC,3,a,b,c); }
int HasInputBeenDetected(int a, int b, int c) { return callNative(0x184830,3,a,b,c); }
int SetRoundWinner(int a, int b, int c) { return callNative(0x196640,3,a,b,c); }
int SyncTime(int a, int b, int c) { return callNative(0x1962DC,3,a,b,c); }
int IsNetworkTimerSyncing(int a, int b, int c) { return callNative(0x1963AC,3,a,b,c); }
int IsNetworkTimerSynced(int a, int b, int c) { return callNative(0x19635C,3,a,b,c); }
int DisconnectFromServer(int a, int b, int c) { return callNative(0x1962A0,3,a,b,c); }
int IsInTrigger(int a, int b, int c) { return callNative(0x195464,3,a,b,c); }
int IsInTriggerList(int a, int b, int c) { return callNative(0x195354,3,a,b,c); }
int IsInCar(int a, int b, int c) { return callNative(0x1951EC,3,a,b,c); }
int IsVehicleCop(int a, int b, int c) { return callNative(0x19288C,3,a,b,c); }
int IsHittingRaceCar(int a, int b, int c) { return callNative(0x1925C4,3,a,b,c); }
int ChangeRaceCar(int a, int b, int c) { return callNative(0x195148,3,a,b,c); }
int SpawnVehicle(int a, int b, int c) { return callNative(0x194E3C,3,a,b,c); }
int TeleportVehicle(int a, int b, int c) { return callNative(0x194BF4,3,a,b,c); }
int ClearResetOnRoad(int a, int b, int c) { return callNative(0x194B6C,3,a,b,c); }
int SetRaceCarInvulnerable(int a, int b, int c) { return callNative(0x194AC4,3,a,b,c); }
int SetRaceCarDamageAllowed(int a, int b, int c) { return callNative(0x194A1C,3,a,b,c); }
int SetEngineState(int a, int b, int c) { return callNative(0x194854,3,a,b,c); }
int SetHeadlightsState(int a, int b, int c) { return callNative(0x194974,3,a,b,c); }
int SetSirenState(int a, int b, int c) { return callNative(0x1948E4,3,a,b,c); }
int ResetAlongRoad(int a, int b, int c) { return callNative(0x194668,3,a,b,c); }
int HasFinishedStreamingWorld(int a, int b, int c) { return callNative(0x1944C4,3,a,b,c); }
int HasFinishedStreamingCameraWorld(int a, int b, int c) { return callNative(0x194468,3,a,b,c); }
int GetPlayerVehicleIndex() { return callNative(0x1943B4,0); }
int GetVehiclePosition(int a, int b, int c) { return callNative(0x199FD4,3,a,b,c); }
int GetPointDistanceToVehicle(int a, int b, int c) { return callNative(0x194194,3,a,b,c); }
int GetPointDistanceSquaredToVehicle(int a, int b, int c) { return callNative(0x197F48,3,a,b,c); }
int GetVehicleDistanceToVehicle(int a, int b, int c) { return callNative(0x193FEC,3,a,b,c); }
int GetVehicleDirection(int a, int b, int c) { return callNative(0x199E50,3,a,b,c); }
int GetSignedVehicleSpeed(int a, int b, int c) { return callNative(0x193F10,3,a,b,c); }
int GetVehicleSpeedMph(int a, int b, int c) { return callNative(0x193D64,3,a,b,c); }
int GetClosingSpeed(int a, int b, int c) { return callNative(0x193B68,3,a,b,c); }
int GetPlayerSpeedMPH(int a, int b, int c) { return callNative(0x193A58,3,a,b,c); }
int GetPlayerTopSpeedMPH(int a, int b, int c) { return callNative(0x193984,3,a,b,c); }
int IsPlayerCarMoving(int a, int b, int c) { return callNative(0x193874,3,a,b,c); }
int GetRaceCarDistanceFromPlayer(int a, int b, int c) { return callNative(0x193110,3,a,b,c); }
int GetTriggerDistanceFromPlayer(int a, int b, int c) { return callNative(0x192F4C,3,a,b,c); }
int GetFirstTriggerIndex(int a, int b, int c) { return callNative(0x192E6C,3,a,b,c); }
int GetNextTriggerIndex(int a, int b, int c) { return callNative(0x192D64,3,a,b,c); }
int GetTriggerPosition(int a, int b, int c) { return callNative(0x199C10,3,a,b,c); }
int GetTriggerDirection(int a, int b, int c) { return callNative(0x1999AC,3,a,b,c); }
int GetTriggerRotation(int a, int b, int c) { return callNative(0x192C80,3,a,b,c); }
int GetTriggerRadius(int a, int b, int c) { return callNative(0x192BF4,3,a,b,c); }
int IsVehicleActive(int a, int b, int c) { return callNative(0x192B30,3,a,b,c); }
int ResetCarDamageLevel(int a, int b, int c) { return callNative(0x193784,3,a,b,c); }
int SetCarDamageLevel(int a, int b, int c) { return callNative(0x1935FC,3,a,b,c); }
int GetCarDamageLevel(int a, int b, int c) { return callNative(0x193524,3,a,b,c); }
int ResetBurstTyres(int a, int b, int c) { return callNative(0x193434,3,a,b,c); }
int SetVulnerableToWrecking(int a, int c) { return callNative(0x19333C,3,a,c); }
int IsVulnerableToWrecking(int a, int b, int c) { return callNative(0x1932C4,3,a,b,c); }
int IsVehiclePhysical(int a, int b, int c) { return callNative(0x19299C,3,a,b,c); }
int IsVehicleLoaded(int a, int b, int c) { return callNative(0x192A6C,3,a,b,c); }
int StopTraffic(int a, int b, int c) { return callNative(0x19241C,3,a,b,c); }
int ResetTraffic(int a, int b, int c) { return callNative(0x1922F8,3,a,b,c); }
int StartTraffic(int a, int b, int c) { return callNative(0x1922BC,3,a,b,c); }
int IsTrafficRunningForCompetitor(int a, int b, int c) { return callNative(0x192248,3,a,b,c); }
int AwardNitrous(int a, int b, int c) { return callNative(0x1921C4,3,a,b,c); }
int SetInfiniteNitrous(int vehicleID, bool enable) { return callNative(0x192114,2,vehicleID,enable); }
int EnableNitrousEarning(int a, int b, int c) { return callNative(0x1920B8,3,a,b,c); }
int ResetNitrousAmount(int a, int b, int c) { return callNative(0x192030,3,a,b,c); }
int EnableKillTrafficAtLocation(int a, int b, int c) { return callNative(0x192458,3,a,b,c); }
int SetTrafficDensity(int a, int b, int c) { return callNative(0x191FA8,3,a,b,c); }
int GetTrafficEntityPosition(int a, int b, int c) { return callNative(0x199858,3,a,b,c); }
int EnablePhysicsEffects(int a, int b, int c) { return callNative(0x191F0C,3,a,b,c); }
int IsCarWrecked(int a, int b, int c) { return callNative(0x191DFC,3,a,b,c); }
int GetSteering(int a, int b, int c) { return callNative(0x191D40,3,a,b,c); }
int SetToughness(int a, int b, int c) { return callNative(0x191C78,3,a,b,c); }
int SetHardStopAllowed(int a, int b, int c) { return callNative(0x191BB0,3,a,b,c); }
int CalculateForwardDirection(int a, int b, int c) { return callNative(0x19A164,3,a,b,c); }
int GetSelectedVehicleId(int a, int b, int c) { return callNative(0x191AC0,3,a,b,c); }
int GetSelectedColourId(int a, int b, int c) { return callNative(0x191A58,3,a,b,c); }
int GetPlayerVehicleToughness(int a, int b, int c) { return callNative(0x191B28,3,a,b,c); }
int AIDrive(int a, int b, int c) { return callNative(0x17FAF4,3,a,b,c); }
int AIDriveAtSpeed(int a, int b, int c) { return callNative(0x17F95C,3,a,b,c); }
int AIDriveInterceptor(int a, int b, int c) { return callNative(0x17F7CC,3,a,b,c); }
int AIBustedBehaviour(int a, int b, int c) { return callNative(0x17F66C,3,a,b,c); }
int AIDrivePlayerAtSpeed(int a, int b, int c) { return callNative(0x180C00,3,a,b,c); }
int GetOpponentVehicleId(int a, int b, int c) { return callNative(0x180AC4,3,a,b,c); }
int GetOpponentColourId(int a, int b, int c) { return callNative(0x180A08,3,a,b,c); }
int DoIntroCutScene(int a, int b, int c) { return callNative(0x17FF1C,3,a,b,c); }
int GetOpponentToughness(int a, int b, int c) { return callNative(0x18095C,3,a,b,c); }
int GetMidRaceJoinPercentage(int a, int b, int c) { return callNative(0x180830,3,a,b,c); }
int GetMidRaceJoinTrigger(int a, int b, int c) { return callNative(0x1806F4,3,a,b,c); }
int HasToActivateOnPlayer(int a, int b, int c) { return callNative(0x17FFD4,3,a,b,c); }
int AIStopDrivingPlayer(int a, int b, int c) { return callNative(0x180B3C,3,a,b,c); }
int IsAIControllingCompetitor(int a, int b, int c) { return callNative(0x180570,3,a,b,c); }
int IsCompetitorTurningAround(int a, int b, int c) { return callNative(0x1804AC,3,a,b,c); }
int IsPlayerFacingCompetitor(int a, int b, int c) { return callNative(0x180354,3,a,b,c); }
int GetFirstAICompetitor(int a, int b, int c) { return callNative(0x180254,3,a,b,c); }
int SetAICompetitorName(int a, int b, int c) { return callNative(0x18017C,3,a,b,c); }
int SetAIRacerName(int a, int b, int c) { return callNative(0x18008C,3,a,b,c); }
int GetPositionAlongRoute(int a, int b, int c) { return callNative(0x198F30,3,a,b,c); }
int ValidateAICarColour(int a, int b, int c) { return callNative(0x17FD14,3,a,b,c); }
int PlayDebugFeedbackSequence(int a, int b, int c) { return callNative(0x1793C8,3,a,b,c); }
int ShowFeedbackMessage(int a, int b, int c) { return callNative(0x18CABC,3,a,b,c); }
int IsMessageInQueue(int a, int b, int c) { return callNative(0x18C8F8,3,a,b,c); }
int RemoveMessage(int a, int b, int c) { return callNative(0x18C808,3,a,b,c); }
int StartFeedbackSequence(int a, int b, int c) { return callNative(0x18C374,3,a,b,c); }
int PrepareFeedbackSequence(int a, int b, int c) { return callNative(0x18C734,3,a,b,c); }
int IsFeedbackSequenceActive(int a, int b, int c) { return callNative(0x18C2C8,3,a,b,c); }
int IsFeedbackSequenceLoaded(int a, int b, int c) { return callNative(0x18C24C,3,a,b,c); }
int IsFeedbackSequenceTriggerActive(int a, int b, int c) { return callNative(0x18BF20,3,a,b,c); }
int IsCutsceneRunning(int a, int b, int c) { return callNative(0x18BE78,3,a,b,c); }
int StopFeedbackSequence(int a, int b, int c) { return callNative(0x18BE04,3,a,b,c); }
int LoadFeedbackGroup(int a, int b, int c) { return callNative(0x18C1DC,3,a,b,c); }
int UnloadFeedbackGroup(int a, int b, int c) { return callNative(0x18C16C,3,a,b,c); }
int IsFeedbackGroupLoaded(int a, int b, int c) { return callNative(0x18C054,3,a,b,c); }
int StartBackgroundSequence(int a, int b, int c) { return callNative(0x18C42C,3,a,b,c); }
int EndBackgroundSequence(int a, int b, int c) { return callNative(0x18C3B8,3,a,b,c); }
int GetCutsceneStartPosition(int a, int b, int c) { return callNative(0x19971C,3,a,b,c); }
int GetCutsceneStartDirection(int a, int b, int c) { return callNative(0x198128,3,a,b,c); }
int IsCutsceneReady(int a, int b, int c) { return callNative(0x18C6D0,3,a,b,c); }
int IsHudMessageQueueEmpty(int a, int b, int c) { return callNative(0x18BD6C,3,a,b,c); }
int AddMapIcon(int a, int b, int c) { return callNative(0x197CF8,3,a,b,c); }
int RemoveMapIcon(int a, int b, int c) { return callNative(0x18B0F8,3,a,b,c); }
int UpdateMapIcon(int a, int b, int c) { return callNative(0x197B84,3,a,b,c); }
int SetCurrentEventRouteHighlighted(int a, int b, int c) { return callNative(0x182DEC,3,a,b,c); }
int ShowLoadingScreen(int a, int b, int c) { return callNative(0x182798,3,a,b,c); }
int IsLoadingScreenShowing(int a, int b, int c) { return callNative(0x18272C,3,a,b,c); }
int ShouldLoadingScreenBeShowing(int a, int b, int c) { return callNative(0x1826C4,3,a,b,c); }
int GetPersonalBest_1(int a, int b, int c) { return callNative(0x18C980,3,a,b,c); }
int IsWebcamAvailable(int a, int b, int c) { return callNative(0x182664,3,a,b,c); }
int SetMapParameters(int a, int b, int c) { return callNative(0x18254C,3,a,b,c); }
int ResetMapParameters(int a, int b, int c) { return callNative(0x182450,3,a,b,c); }
int SetLayoutSet(int a, int b, int c) { return callNative(0x182C8C,3,a,b,c); }
int SetLayoutSetOverride(int a, int b, int c) { return callNative(0x182D3C,3,a,b,c); }
int HasLayoutGroupLoaded(int a, int b, int c) { return callNative(0x182BAC,3,a,b,c); }
int ClearLayoutSetOverride(int a, int b, int c) { return callNative(0x182B3C,3,a,b,c); }
int ClearLoadingScreenLayout(int a, int b, int c) { return callNative(0x182AD4,3,a,b,c); }
int GetCurrentLayoutSet(int a, int b, int c) { return callNative(0x182A4C,3,a,b,c); }
int TryPopPageFromHistory(int a, int b, int c) { return callNative(0x1823FC,3,a,b,c); }
int SetMapIconVisibilty(int a, int b, int c) { return callNative(0x18B04C,3,a,b,c); }
int GetChallengeLoadingScreenID(int a, int b, int c) { return callNative(0x1829B4,3,a,b,c); }
int GetChallengeOutroScreenID(int a, int b, int c) { return callNative(0x18291C,3,a,b,c); }
int SetNormalMessageMode(int a, int b, int c) { return callNative(0x1823C0,3,a,b,c); }
int ClearAllFeedbackQueues(int a, int b, int c) { return callNative(0x18B6EC,3,a,b,c); }
int ClearAllNonBackgroundFeedbackQueues(int a, int b, int c) { return callNative(0x18B654,3,a,b,c); }
int AreUnitsMetric(int a, int b, int c) { return callNative(0x18BD24,3,a,b,c); }
int ShowForcedFeedBackMessage(int a, int b, int c) { return callNative(0x18D0F8,3,a,b,c); }
int PlaySound(int a, int b, int c) { return callNative(0x18BBFC,3,a,b,c); }
int StopSound(int a, int b, int c) { return callNative(0x18B760,3,a,b,c); }
int StopAllSounds(int a, int b, int c) { return callNative(0x18B9DC,3,a,b,c); }
int PlaySoundAtPlayer(int a, int b, int c) { return callNative(0x18BA34,3,a,b,c); }
int IsSoundInQueue(int a, int b, int c) { return callNative(0x18B5CC,3,a,b,c); }
int PlayMusic(int a, int b, int c) { return callNative(0x18B55C,3,a,b,c); }
int StopMusic(int a, int b, int c) { return callNative(0x18B988,3,a,b,c); }
int PlaySpeech(int a, int b, int c) { return callNative(0x18B478,3,a,b,c); }
int StopSpeech(int a, int b, int c) { return callNative(0x18B8D8,3,a,b,c); }
int PlayGameplayStream(int a, int b, int c) { return callNative(0x18B318,3,a,b,c); }
int StopGameplayStream(int a, int b, int c) { return callNative(0x18B930,3,a,b,c); }
int StopUnwantedSound(int a, int b, int c) { return callNative(0x18B850,3,a,b,c); }
int ApplyMixSnapshotSet(int a, int b, int c) { return callNative(0x18B28C,3,a,b,c); }
int ClearMixSnapshotSet(int a, int b, int c) { return callNative(0x18B228,3,a,b,c); }
int IsSkipCutsceneButtonPressed(int a, int b, int c) { return callNative(0x182348,3,a,b,c); }
int RequestSkipSequence(int a, int b, int c) { return callNative(0x1822A4,3,a,b,c); }
int EnableOnlineMessages(int a, int b, int c) { return callNative(0x182218,3,a,b,c); }
int EnableCrashAssistMessages(int a, int b, int c) { return callNative(0x18218C,3,a,b,c); }
int RequestBustLocalPlayer(int a, int b, int c) { return callNative(0x19011C,3,a,b,c); }
int GetBustedQueueLength(int a, int b, int c) { return callNative(0x1900B8,3,a,b,c); }
int GetBustedVictimInQueue(int a, int b, int c) { return callNative(0x19001C,3,a,b,c); }
int GetBustingAggressorInQueue(int a, int b, int c) { return callNative(0x18FF80,3,a,b,c); }
int IsBustSequenceInProgress(int a, int b, int c) { return callNative(0x18FEFC,3,a,b,c); }
int SetPursuitRulesEnabled(int a, int b, int c) { return callNative(0x18FAA8,3,a,b,c); }
int ArePursuitRulesEnabled(int a, int b, int c) { return callNative(0x18FA58,3,a,b,c); }
int StartPursuit(int a, int b, int c) { return callNative(0x18F9C8,3,a,b,c); }
int EndPursuit(int a, int b, int c) { return callNative(0x18F6C4,3,a,b,c); }
int IsInPursuit(int a, int b, int c) { return callNative(0x18F208,3,a,b,c); }
int IsCompetitorInPursuit(int a, int b, int c) { return callNative(0x18F50C,3,a,b,c); }
int UpdateFelonyBar(int a, int b, int c) { return callNative(0x18F77C,3,a,b,c); }
int GetNumPursuers(int a, int b, int c) { return callNative(0x18F15C,3,a,b,c); }
int GetPursuer(int a, int b, int c) { return callNative(0x18F070,3,a,b,c); }
int GetNumPursuitTargets(int a, int b, int c) { return callNative(0x18EF88,3,a,b,c); }
int GetPursuitTarget(int a, int b, int c) { return callNative(0x18EEA0,3,a,b,c); }
int GetPursuitTargetDistance(int a, int b, int c) { return callNative(0x18ED80,3,a,b,c); }
int GetLastPursuitOutcome(int a, int b, int c) { return callNative(0x18ED1C,3,a,b,c); }
int SendCancelCooldownMessage(int a, int b, int c) { return callNative(0x18EBC0,3,a,b,c); }
int GetPlayerLevel(int a, int b, int c) { return callNative(0x18E5A4,3,a,b,c); }
int RemoveScoringMessages(int a, int b, int c) { return callNative(0x18E9E8,3,a,b,c); }
int ShowPursuitCooldown(int a, int b, int c) { return callNative(0x18EB2C,3,a,b,c); }
int IsInPursuitCooldown(int a, int b, int c) { return callNative(0x18EAD4,3,a,b,c); }
int GetCurrentPursuitBounty(int a, int b, int c) { return callNative(0x18EA3C,3,a,b,c); }
int IsCompetitorBeingJammed(int a, int b, int c) { return callNative(0x18E958,3,a,b,c); }
int SetCompetitorBeingJammed(int a, int b, int c) { return callNative(0x18E8A0,3,a,b,c); }
int SetCompetitorHitByEMP(int a, int b, int c) { return callNative(0x18E810,3,a,b,c); }
int IsCompetitorEliminated(int a, int b, int c) { return callNative(0x18E790,3,a,b,c); }
int SetCompetitorEliminated(int a, int b, int c) { return callNative(0x18E700,3,a,b,c); }
int SetCompetitorHighlighted(int a, int b, int c) { return callNative(0x18E670,3,a,b,c); }
int IsCompetitorHidden(int a, int b, int c) { return callNative(0x18E524,3,a,b,c); }
int SetCompetitorHidden(int a, int b, int c) { return callNative(0x18E494,3,a,b,c); }
int CopCount(int a, int b, int c) { return callNative(0x190D6C,3,a,b,c); }
int RacerCount(int a, int b, int c) { return callNative(0x190D00,3,a,b,c); }
int SetPursuitRangeIconDisabled(int a, int b, int c) { return callNative(0x18FC00,3,a,b,c); }
int IsSirenButtonPressed(int a, int b, int c) { return callNative(0x190454,3,a,b,c); }
int SetCopSiren(int a, int b, int c) { return callNative(0x1902B8,3,a,b,c); }
int IsCompetitorCop(int a, int b, int c) { return callNative(0x190DD8,3,a,b,c); }
int GetClosestCop(int a, int b, int c) { return callNative(0x190AC4,3,a,b,c); }
int GetClosestCopDistance(int a, int b, int c) { return callNative(0x190844,3,a,b,c); }
int GetClosestRacer(int a, int b, int c) { return callNative(0x190608,3,a,b,c); }
int GetClosestRacerDistance(int a, int b, int c) { return callNative(0x190590,3,a,b,c); }
int GetMostVisibleRival(int a, int b, int c) { return callNative(0x1904CC,3,a,b,c); }
int CanBePursued(int a, int b, int c) { return callNative(0x18E388,3,a,b,c); }
int SetCanBePursued(int a, int b, int c) { return callNative(0x18E290,3,a,b,c); }
int GetNumCopsInPursuit(int a, int b, int c) { return callNative(0x18E230,3,a,b,c); }
int SetAIDriver(int a, int b, int c) { return callNative(0x18FB0C,3,a,b,c); }
int OnEscape(int a, int b, int c) { return callNative(0x18D48C,3,a,b,c); }
int SetVictimStrike(int a, int b, int c) { return callNative(0x1903D8,3,a,b,c); }
int SetAggressorStrike(int a, int b, int c) { return callNative(0x19035C,3,a,b,c); }
int AreAllRacersBusted(int a, int b, int c) { return callNative(0x18D380,3,a,b,c); }
int IsCopWrecked(int a, int b, int c) { return callNative(0x18D1F8,3,a,b,c); }
int SetCopScorePerBust(int a, int b, int c) { return callNative(0x18D678,3,a,b,c); }
int OnCopAddedToHotPursuit(int a, int b, int c) { return callNative(0x18FC98,3,a,b,c); }
int HasCopEverBustedRacer(int a, int b, int c) { return callNative(0x18D5BC,3,a,b,c); }
int HasRacerEverEscapedCop(int a, int b, int c) { return callNative(0x18D500,3,a,b,c); }
int GetPursuitRuleParam(int a, int b, int c) { return callNative(0x18DDB4,3,a,b,c); }
int GetPursuitRuleParamCount(int a, int b, int c) { return callNative(0x18E10C,3,a,b,c); }
int ResetPursuitLogic(int a, int b, int c) { return callNative(0x18DD6C,3,a,b,c); }
int SetPursuitCooldownEnabled(int a, int b, int c) { return callNative(0x18DD08,3,a,b,c); }
int SetPursuitUseRacePositionForRoadBlock(int a, int b, int c) { return callNative(0x18DCA4,3,a,b,c); }
int SetPursuitUseSilentPursuitStarts(int a, int b, int c) { return callNative(0x18DC40,3,a,b,c); }
int SetEnableSpikeStripWrecking(int a, int b, int c) { return callNative(0x18DBDC,3,a,b,c); }
int SetCopDelayRespawnAfterWrecking(int a, int b, int c) { return callNative(0x18DB34,3,a,b,c); }
int EnableCopLongBusts(int a, int b, int c) { return callNative(0x18DAD0,3,a,b,c); }
int EnableRacerRespawnAfterBust(int a, int b, int c) { return callNative(0x18DA6C,3,a,b,c); }
int SetRacerRespawn_LocalPlayerRespawnAfterBust(int a, int b, int c) { return callNative(0x18D9C8,3,a,b,c); }
int SetRacerRespawn_TeleportAlongRaceLine(int a, int b, int c) { return callNative(0x18D924,3,a,b,c); }
int SetRacerRespawn_TeleportAfterBust(int a, int b, int c) { return callNative(0x18D880,3,a,b,c); }
int SetCopRespawn_TeleportAlongRaceLine(int a, int b, int c) { return callNative(0x18D7DC,3,a,b,c); }
int SetCopRespawn_TeleportAfterBust(int a, int b, int c) { return callNative(0x18D738,3,a,b,c); }
int SetAICopDoPostBustCallback(int a, int b, int c) { return callNative(0x18D6D4,3,a,b,c); }
int SetKillerBlowWreckingEnabled(int a, int b, int c) { return callNative(0x18D284,3,a,b,c); }
int SetFriendlyFireOn(int a, int b, int c) { return callNative(0x18FE90,3,a,b,c); }
int SetAllowLowSpeedBustsWhenCrashing(int a, int b, int c) { return callNative(0x18FE24,3,a,b,c); }
int SetBustingEndsPursuits(int a, int b, int c) { return callNative(0x18FDC0,3,a,b,c); }
int SetOnlyMostWantedCanEnterCooldown(int a, int b, int c) { return callNative(0x18FD5C,3,a,b,c); }
int GetScriptInstanceCount(int a, int b, int c) { return callNative(0x1817E8,3,a,b,c); }
int GetWorldScriptIDFromIndex(int a, int b, int c) { return callNative(0x181750,3,a,b,c); }
int IsScriptInstanceLoaded(int a, int b, int c) { return callNative(0x18162C,3,a,b,c); }
int LoadScriptInstance(int a, int b, int c) { return callNative(0x1814B4,3,a,b,c); }
int UnloadScriptInstance(int a, int b, int c) { return callNative(0x18144C,3,a,b,c); }
int ResumeWorldScript(int a, int b, int c) { return callNative(0x1813E4,3,a,b,c); }
int PauseWorldScript(int a, int b, int c) { return callNative(0x18137C,3,a,b,c); }
int ResetWorldScript(int a, int b, int c) { return callNative(0x181314,3,a,b,c); }
int IsScriptInstancePaused(int a, int b, int c) { return callNative(0x181520,3,a,b,c); }
int GetWorldScriptParameterTable(int a, int b, int c) { return callNative(0x181208,3,a,b,c); }
int SetWorldBehaviour(int a, int b, int c) { return callNative(0x180FB0,3,a,b,c); }
int SetWorldBehaviourAggregator(int a, int b, int c) { return callNative(0x180EC8,3,a,b,c); }
int IsWorldEffectOn(int a, int b, int c) { return callNative(0x180E04,3,a,b,c); }
int GetWorldEffectValue(int a, int b, int c) { return callNative(0x180D44,3,a,b,c); }
int GetLocalWorldEffectValue(int a, int b, int c) { return callNative(0x17F5AC,3,a,b,c); }
int GetWorldScriptPlacementID(int a, int b, int c) { return callNative(0x1810F0,3,a,b,c); }
int TransitionCameraToLocation(int a, int b, int c) { return callNative(0x1978CC,3,a,b,c); }
int TransitionCameraToGameplay(int a, int b, int c) { return callNative(0x195D98,3,a,b,c); }
int SetCameraTransitionLocation(int a, int b, int c) { return callNative(0x19769C,3,a,b,c); }
int CalculateInterpolatedLocation(int x, int y) { return callNative(0x198264, 3, x, y); }
int CalculateRotatedLocationXZ(int a, int b, int c) { return callNative(0x19A3AC,3,a,b,c); }
int GetCameraPosition(int a, int b, int c) { return callNative(0x198E1C,3,a,b,c); }
int GetCameraDirection(int a, int b, int c) { return callNative(0x198D08,3,a,b,c); }
int GetGameplayCameraPosition(int a, int b, int c) { return callNative(0x198BD8,3,a,b,c); }
int SnapCameraToBehindCar(int a, int b, int c) { return callNative(0x195F8C,3,a,b,c); }
int GetCameraFov(int a, int b, int c) { return callNative(0x195F24,3,a,b,c); }
int SetCameraFov(int a, int b, int c) { return callNative(0x195EB8,3,a,b,c); }
int ResetCameraFov(int a, int b, int c) { return callNative(0x195E54,3,a,b,c); }
int CycleCameraTarget(int a, int b, int c) { return callNative(0x1959D0,3,a,b,c); }
int ResetCameraTarget(int a, int b, int c) { return callNative(0x195964,3,a,b,c); }
int GetCameraTarget(int a, int b, int c) { return callNative(0x1958FC,3,a,b,c); }
int SetUseOverheadCamera(int a, int b, int c) { return callNative(0x195888,3,a,b,c); }
int GetUseOverheadCamera(int a, int b, int c) { return callNative(0x19582C,3,a,b,c); }
int SetUseFinishLineCamera(int a, int b, int c) { return callNative(0x195780,3,a,b,c); }
int IsSpectatorCameraButtonPressed(int a, int b, int c) { return callNative(0x1956FC,3,a,b,c); }
int AllowCameraSwitching(int a, int b, int c) { return callNative(0x195694,3,a,b,c); }
int SetUseDebugCamera(int a, int b, int c) { return callNative(0x195658,3,a,b,c); }
int OverwriteDebugCameraState(int a, int b, int c) { return callNative(0x19561C,3,a,b,c); }
int ClearOverwriteDebugCameraState(int a, int b, int c) { return callNative(0x1955E0,3,a,b,c); }
int SetCameraTargetFromTrigger(int a, int b, int c) { return callNative(0x195BE4,3,a,b,c); }
int SwitchToIceCamera(int a, int b, int c) { return callNative(0x196148,3,a,b,c); }
int StopUsingIceCamera(int a, int b, int c) { return callNative(0x1960E0,3,a,b,c); }
int SetIceCameraPaused(int a, int b, int c) { return callNative(0x196050,3,a,b,c); }
int GetIceTakeDuration(int a, int b, int c) { return callNative(0x195FE4,3,a,b,c); }
int GetLocalPlayerScore(int a, int b, int c) { return callNative(0x191998,3,a,b,c); }
int GetPlayerScore(int a, int b, int c) { return callNative(0x191998,3,a,b,c); }
int SetLocalPlayerScore(int a, int b, int c) { return callNative(0x1918FC,3,a,b,c); }
int GetCompetitorRacePosition(int a, int b, int c) { return callNative(0x191824,3,a,b,c); }
int SetCompetitorRacePosition(int a, int b, int c) { return callNative(0x191748,3,a,b,c); }
int GetDistanceToCheckpoint(int a, int b, int c) { return callNative(0x191648,3,a,b,c); }
int EnableRoadTimes(int a, int b, int c) { return callNative(0x19158C,3,a,b,c); }
int HasRoadRuleFinished(int a, int b, int c) { return callNative(0x191528,3,a,b,c); }
int GetCurrentRoadTime(int a, int b, int c) { return callNative(0x191460,3,a,b,c); }
int LockRoadRule(int a, int b, int c) { return callNative(0x191304,3,a,b,c); }
int UnlockRoadRules(int a, int b, int c) { return callNative(0x1912B0,3,a,b,c); }
int WasRoadRuleSuccessful(int a, int b, int c) { return callNative(0x191234,3,a,b,c); }
int EnableBountyEarning(int a, int b, int c) { return callNative(0x1911C4,3,a,b,c); }
int SetEveryoneUsesRaceBalancing(int a, int b, int c) { return callNative(0x19115C,3,a,b,c); }
int SendMostWantedLobbyState(int a, int b, int c) { return callNative(0x191108,3,a,b,c); }
int SendMostWantedEndMessage(int a, int b, int c) { return callNative(0x190ED0,3,a,b,c); }
int SetMostWantedDisconnected(int a, int b, int c) { return callNative(0x190E78,3,a,b,c); }
int GetWeaponName(int a, int b, int c) { return callNative(0x1820DC,3,a,b,c); }
int GetDistanceToWeapon(int a, int b, int c) { return callNative(0x181D48,3,a,b,c); }
int IsHelicopterWeaponActive(int a, int b, int c) { return callNative(0x181FAC,3,a,b,c); }
int RemoveAllWeapons(int a, int b, int c) { return callNative(0x181CFC,3,a,b,c); }
int SetWeaponCooldownTime(int a, int b, int c) { return callNative(0x181CA4,3,a,b,c); }
int FireRoadBlockAtLeader(int a, int b, int c) { return callNative(0x181AA0,3,a,b,c); }
int FireHelicopterAtLeader(int a, int b, int c) { return callNative(0x1818B0,3,a,b,c); }
int SetSuppressCopWeaponMessages(int a, int b, int c) { return callNative(0x181848,3,a,b,c); }
int GetPlayerWeaponLevel(int a, int b, int c) { return callNative(0x182024,3,a,b,c); }
int ResetWeaponAvailablilty(int a, int b, int c) { return callNative(0x181E50,3,a,b,c); }
int SetupWeaponAvailabilityForCompetitor(int a, int b, int c) { return callNative(0x181F10,3,a,b,c); }
int ResetWeaponUseDelayTimer(int a, int b, int c) { return callNative(0x181EBC,3,a,b,c); }
int ExitState(int a, int b, int c) { return callNative(0xF09A8,3,a,b,c); }
int IsHsmStateRunning(int a, int b, int c) { return callNative(0xFCD80,3,a,b,c); }


